version: '3.7'
services:

  back:
    build:
      context: ./laravel
    image: keycloak-app-back
    container_name: keycloak-app-back
    entrypoint: /app/.docker/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - ./laravel:/app
    depends_on:
      - database

  front:
    build:
      context: ./next
    image: keycloak-app-front
    container_name: keycloak-app-front
    entrypoint: /app/.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./next:/app
    depends_on:
      - back

  database:
    image: mysql:latest
    container_name: keycloak-app-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - database-data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command: 
      - start-dev 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database-data: